# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd26f37b52233ddaa702771bfd0a13453a2feb6ab524f7da9e90f51508b02b6638c0f92009fabf28d89415632481a608a221463e4b0ad36f1ecacc0b1f17db6f

test:
  secret_key_base: 116a05c26bd1b5db83234ee392f9276a3490e1caed98a3ab43a1052348e7108900499aa5b13787a4be58297ccba42abb6c31449de5f68ea7655f459be6775f4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
